baseURL = "https://22.220779.xyz/"
languageCode = "zh-CN"
title = "我的书签导航"
theme = "hugo-webstack"
disablePathToLower = true
copyright = "lgxbh"

[params]
  keywords = "网址导航,webstack,书签,导航"
  description = "个人书签导航站，341个书签，15个分类"

[params.search]
  enable = true

[params.darkmode]
  enable = false

[params.edit]
  enable = true
  url = "https://github.com/lgxbh2010/my-nav-station/blob/main/data/webstack.yml"

[params.github]
  enable = true
  url = "https://github.com/lgxbh2010/my-nav-station"

[permalinks]
  404 = "/404.html"

[params.pinyin]
  enable = true
